### ISSUE TITLE
Publish Secrets to Azure Key vault is failing- "Error occurred demo"

### ISSUE THREAD

**Issue by chintupawan** [onlyutkarsh/utkarsh-utility-tasks#15]
![image](https://user-images.githubusercontent.com/1989514/57996494-e2becf80-7b1b-11e9-880e-cea735151985.png)

There is no such word "Demo" in my pipeline or variables. This is widely used in my pipelines. All of them are failing all of a sudden. 

Any help would be appreciated.

**Comment by onlyutkarsh** [comment]
That is a bug in the task. Will push the fix in few hours.

**Comment by onlyutkarsh** [comment]
I have fixed now. Please try and let me know. Ensure you are using task v1.0.31 in the tool-tip.

![image](https://user-images.githubusercontent.com/2685029/57998384-2cca9580-7ac9-11e9-8b2b-828d8afd8919.png)

**Comment by chintupawan** [comment]
its working now. Thanks for the quick response. really appreciate your work 👍
