### ISSUE TITLE
Publish Secrets to Azure Key Vault trims '==' from end of secret.

### ISSUE THREAD

**Issue by msivers** [onlyutkarsh/utkarsh-utility-tasks#5]
I am trying to publish a Cosmos DB key to Key Vault but the trailing '==' characters are omitted.

For example...
Ws2Fy9aOWRpEQ4Fep6Yp80acJmNknEYcMO63A5XvxJ2kmq2dSvvL4519TgcvGNlyHS7PTXNkPiR1XdYs2dQiOA==

Gets saved as...
Ws2Fy9aOWRpEQ4Fep6Yp80acJmNknEYcMO63A5XvxJ2kmq2dSvvL4519TgcvGNlyHS7PTXNkPiR1XdYs2dQiOA

**Comment by onlyutkarsh** [comment]
@msivers thanks for raising it. I think I have a fix for this. Will test and publish soon.

**Comment by onlyutkarsh** [comment]
@msivers sorry for the delay on this one - I had really busy days in office from last few weeks and was unable to spend my evenings to investigate this issue. I just released the new version (v1.0.4). 

![image](https://user-images.githubusercontent.com/2685029/49701681-3204e980-fbe7-11e8-9fa9-38f2f806c7d6.png)

I checked your secret above with the new version, and it seems to be working. Please check you have the correct version and let me know if it works for you.
